seo:
  site_name: Hatha Vinyasa Yoga in Schwyz – Sun Moon Yoga Studio
  title: Hatha Vinyasa Yoga in Schwyz – Sun Moon Yoga Studio
  description: Entdecke Hatha Vinyasa Yoga mit Juliana in Schwyz – online oder vor Ort. Sanfte Flows, bewusste Atmung und tiefe Entspannung. Jetzt Yogastunde ab CHF 15 buchen.
  social_image: /images/sunmoonyogastudio-header-banner.jpg
  keywords: Hatha Yoga Schwyz, Vinyasa Yoga Schwyz, Yoga Schwyz, Yoga Online Schweiz, Yoga Stunden Schwyz, Yoga Kurse Schwyz, Sun Moon Yoga 
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#000000'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#3c3c41'
  medium_color: '#98A9B7'
  light_color: '#F4F1E8'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
